export default {
    "label":"环评测试",
    "name":"eia_test",
    "type":"tab",
    "children":[{
        "label":"排污测试",
        "name":"emission_test",
        "type":"tab",
        "children":[{
            "label":"废气污染物",
            "name":"exhaust_pollutants",
            "type":"input",
            "value":""
        },
        {
            "label":"固废污染物",
            "name":"solid_waste_pollutants",
            "type":"checkbox",
            "value":""
        }]
    },
    {
        "label":"法人信息",
        "name":"legal_person_information",
        "type":"tab",
        "children":[{
            "label":"公司名称",
            "name":"corporate_name",
            "type":"radio",
            "value":""
        }]
    }]
}